name: closecart
description: "A mobile app that helps users discover nearby shops and exclusive offers based on their location. Features include offer discovery, shop information, and favorites management."
publish_to: "none"
version: 1.3.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  dart_jsonwebtoken: ^2.17.0
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter:
    sdk: flutter

  flutter_map: ^5.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  hive_flutter: ^1.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  latlong2: ^0.9.0
  provider: ^6.1.2
  shared_preferences: ^2.0.6
  shimmer: ^3.0.0
  toastification: ^1.0.0
  url_launcher: ^6.3.1
  # flutter_launcher_icons: ^0.14.3
  # change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic

    - family: Lato Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
          style: italic

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.jpg"
