name: closecart
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  http: ^1.3.0
  provider: ^6.1.2
  shared_preferences: ^2.0.6
  shimmer: ^3.0.0
  toastification: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic

    - family: Lato Black
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
          style: italic

  uses-material-design: true
